### PR TITLE
fix: invalid h5 block

### PR DESCRIPTION
**Pull request by shikaan**
Hello 👋 

I think I have found a bug: the CSS does not appear to be parseable. I have patched this in a project, but maybe some other people may benefit from this.

Thanks for the great work!

### CODE REVIEW

**Comment by punund** [comment]
This also applies to `pre` and `blockquote`.
Must be a string copied over.

**Comment by shikaan** [comment]
Hey @punund, thanks for the head-sup. I have updated the PR accordingly :)

**Comment by shikaan** [comment]
Hey @mblode any chance we can get this moving? Can I help somehow?

**Comment by mblode** [comment]
Sorry for the delay everyone! GitHub notifications suck. This is now merged 😄

**Pull request merged**
